---
title: "Estimación con n parcelas ubicadas uniformemente al azar y de forma independiente"
output:
  html_document: default
---

#### Introducción

En esta pestaña se explica cómo se hace la estimación de un parámetro de interés (ver pestaña **Población**) cuando se repite $n$ veces y de forma independiente el experimento aleatorio de:

1.  Seleccionar $n$ ubicaciones al azar en la zona a muestrear

2.  Seleccionar los árboles que compondrán la muestra en cada una de las $n$ parcelas en base al tipo de parcela empleado.

3.  Obtener $n$ estimadores de parcela y promediarlos. Al resultado de este promedio los llamaremos **estimador final**

#### Estimador final y propiedades

Cuando medimos múltiples parcelas ubicadas al azar y de forma independiente, construimos nuestro estimador final promediando los $n$ estimadores de parcela que se calculan como se explica en la pestaña anterior.

$$\boxed{\boxed{ estimador final = \frac{1}{n}\sum_{p=1}^n (estimador~parcela)_p}}$$

Para conocer las propiedades del estimador final debemos tener en cuenta las siguientes ideas:

1.  Los estimadores de parcela son variables aleatorias (heredan la aleatoriedad de la ubicación del punto de muestreo) y todas proceden del mismo experimento y por tanto tienen la misma distribución.

2.  Cómo las ubicaciones de las $n$ parcela se establece de forma independiente, tenemos que el estimador final es una media de $n$ variables aleatorias independientes, y todas con la misma distribución por ser repeticiones del mismo experimento.

A partir de estos dos puntos podemos deducir propiedades importantes del estimador final. Para ello, simplemente tenemos que recordar algunas propiedades de las esperanzas y varianzas de combinaciones lineales de variables aleatorias vistas en estadística.

#### Valor esperado del estimador final

-   La esperanza de una suma de $n$ variables aleatorias es igual a la suma de las esperanzas. $E(\sum_{p=1}^n x_p)=\sum_{p=1}^nE(x_p)$

-   La esperanza de una variable aleatoria $x$ por una constante $k$ es igual a la constante por la esperanza de la variable aleatoria. $E(k x) = kE(x)$

En base a estas propiedades tenemos que:

$$E(estimador final) = E(\frac{1}{n}\sum_{p=1}^n (estimador~parcela)_p)=\frac{1}{n}\sum_{p=1}^n E(estimador~parcela_p)$$

Como todos los estimadores de parcela tiene son el resultado del mismo experimento aleatorio, todos tienen la misma esperanza y tenemos que:

$$\boxed{\boxed{ E(estimador final) = \frac{nE(estimador~parcela)}{n}=E(estimador~parcela)}}$$

El estimador final tendrá la misma esperanza que el estimador de parcela. Esto es interesante porque:

-   Para totales y totales por unidad de área, el valor esperado del estimador de parcela coincide con el parámetro a estimar si los efectos de bordes son pequeños. Es decir, los estimadores de parcela no tienen sesgo, y los estimadores finales heredan esta propiedad.

$$\boxed{\boxed{ E(estimador final) = E(estimador~parcela)=Parámetro~interés}}$$

-   Para ratios, funciones de totales y parámetros complejos, el valor esperado no coincidirá con el parámetro a estimar, es decir, los estimadores de parcela pueden tener un sesgo y este lo heredará el estimador final.

#### Varianza y desviación típica del estimador final

Para obtener la varianza del estimador final nos apoyaremos en:

-   La varianza de una suma de $n$ variables aleatorias **independientes** es igual a la suma de sus varianzas. $V(\sum_{p=1}^n x_p)=\sum_{p=1}^nV(x_p)$

-   La varianza de una variable aleatoria $x$ por una constante $k$ es igual a la constante al cuadrado por la varianza de la variable aleatoria. $V(k x) = k²V(x)$

En base a estas propiedades tenemos que:

$$V(estimador final) = V(\frac{1}{n}\sum_{p=1}^n (estimador~parcela_p))=\frac{1}{n²}\sum_{p=1}^n V(estimador~parcela_p)$$

Como todos los estimadores de parcela son el resultado de repetir el mismo experimento aleatorio, todos tiene la misma varianza y tenemos que:

$$\boxed{\boxed{ V(estimador final) = \frac{nV(estimador~parcela)}{n²}=\frac{V(estimador~parcela)}{n}}}$$

La varianza del estimador será igual a $\frac{1}{n}$ por la varianza del estimador de parcela. Sin el lugar de a las varianzas miramos desviaciones típica, $sd=\sqrt{V}$, al tomar raíces cuadradas tendremos que la desviación típica del estimador final será $\frac{1}{\sqrt{n}}$ por la desviación típica del estimador de parcela.

$$\boxed{\boxed{ sd(estimador final) =\sqrt{\frac{V(estimador~parcela)}{n}}=\frac{sd(estimador~parcela)}{\sqrt{n}}}}$$


#### **Panel izquierdo, Población, muestras y estimaciones**

Antes de continuar, se recomienda pulsar el botón **Regenera población** para no acumular muestras de las pruebas realizadas en pestañas anteriores. Además, en esta pestaña es posible aumentar el número de parcelas que se miden empleando el control para el **Número de parcelas** o los botones de **Aumenta n** y **Reduce n**.

Para un número de parcelas dado, cada vez que se pulsa el botón **Muestrea** se tonan $n$ parcelas y se calculan sus estimadores de parcela. Finalmente, se obtiene el estimador final promediando las $n$ estimaciones de parcela.

En el panel izquierdo puedes ver los valores de distintos parámetros de interés, las parcelas generadas, así como las estimaciones de parcela para cada una de las $n$ parcelas.

#### **Panel derecho comparación estimaciones por parcela vs estimaciones finales (promedio** $n$ **estimaciones por parcela)**

En el panel derecho se puede comparar la distribución de las estimaciones por parcela (panel superior en rojo) con la distribución de las estimaciones finales (panel inferior punto en azul). Igual que en la pestaña anterior el valor real del parámetro de interés se marca con una línea vertical roja.

A medida que pulsamos el botón **Muestrea** vamos aproximándonos a la distribución muestral de los estimadores de parcela y de los estimadores finales (medias de las $n$ estimaciones de parcela de cada iteración). Es importante fijarse en que al aumentar $n$ la variabilidad de las estimaciones finales se reduce. La variabilidad de las estimaciones por parcela y de las estimaciones finales se indica con un segmento horizontal de color rojo cuyo ancho es dos veces la desviación típica de las estimaciones finales o de parcela (según corresponda). En la siguiente pestaña se ve en más detalle gráficamente como es esa reducción, pero en base a las formulas vistas en esta pestaña podemos saber que:

1.  $V(estimador final)$ disminuirá de forma inversamente proporcional a $n$

2.  $sd(estimador final)$, que da una idea del ancho de la distribución muestral, disminuirá de forma inversamente proporcional a $\sqrt{n}$
