---
title: "Dimensionamiento de muestra para un error dado"
output:
  html_document: default
---

#### Introducción

En la pestaña anterior hemos visto cómo calcular intervalos de confianza y errores de muestreo (absolutos o relativos). En esta pestaña veremos cómo se procede para calcular el número de parcelas que hay que realizar para conseguir un error de muestreo determinado. Para hacer este cálculo no necesitamos nada nuevo, simplemente nos apoyaremos en un muestreo piloto y en las fórmulas de la desviación típica del estimador final y del error relativo.

$$\hat{sd}(\hat{\mu}_{final})=\frac{\hat{sd}(\hat{\mu}_p)}{\sqrt{n}}$$

$$\hat{\varepsilon}_{(1-\alpha)\%} = \frac{q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})}{\hat{\mu}_{final}}$$

En la segunda ecuación igualamos el error en función de $n$ y de los requisitos de error que nos han dado. Si sustituimos la primera ecuación en la segunda, tendremos:

$$\hat{\varepsilon}_{(1-\alpha)\%} = \frac{q(1-\frac{\alpha}{2})}{\hat{\mu}_{final}} \frac{\hat{sd}(\hat{\mu}_p)}{\sqrt{n}}$$

Operando, tenemos que para un nivel de probabilidad fiducial y error relativo determinado tendremos que:

$$\frac{\hat{\varepsilon}_{(1-\alpha)\%}\hat{\mu}_{final}}{q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_p)} = \frac{1}{\sqrt{n}} \rightarrow  \boxed{\boxed{n = {\left( \frac{q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_p)}{\hat{\varepsilon}_{(1-\alpha)\%}\hat{\mu}_{final}}\right)}^2}}$$

Sabemos como obtener todos los términos de la fórmula anterior para $n$, pero para obtener $\hat{\mu}_{final}$ y $\hat{sd}(\hat{\mu}_p)$ necesitamos una muestra y ahí es donde entra en juego el muestreo piloto. Un muestreo piloto es un muestreo preliminar con un número relativamente reducido de parcelas que fijamos nosotros y que emplearemos para poder tener valores de $\hat{\mu}_{final}$ y $\hat{sd}(\hat{\mu}_p)$ de forma que podamos calcular un $n$ para el nivel de error requerido.

#### Cálculo práctico de n

Lo primero que haremos para determinar $n$ es el muestreo piloto. Una vez midamos las parcelas piloto, haremos lo siguiente:

1.  Obtendremos el estimador final $\hat{\mu}_{final}$ como promedio de los estimadores de parcela en las parcelas piloto. El número de parcelas piloto lo indicaremos con $n_{piloto}$ .
2.  Estimamos la desviación típica del estimador de parcela $\hat{\mu}_{final}$ usando:

$$\hat{sd}(\hat{\mu}_{p})=\sqrt{\frac{\sum_{i=1}^p(\hat{\mu}_p-\hat{\mu}_{final})^2}{(n_{piloto}-1)}}$$

3.  Obtenemos el valor de $q(1-\frac{\alpha}{2})$. Si usas $q(1-\frac{\alpha}{2})$ basado en una distribución t-student, el número de grados de libertad será $n_{piloto}-1$. Una vez que hemos calculado los tres valores anteriores, sólo tenemos que sustituir en la fórmula de $n$.

**Ejemplo 1:**

Nos solicitan estimar el volumen por hectárea en un monte y dar estimaciones con un error relativo inferior al 10% al 95% de probabilidad fiducial. Hacemos un muestreo piloto con $n_{piloto}=10$ parcelas. En base a nuestro muestreo piloto tenemos que:

1.  El valor estimado del volumen en base a las 10 parcelas piloto es $\mu_{final}=315 m³/ha$

2.  El valor estimado de la desviación típica del estimador de parcela de $sd(\hat{\mu_{final}})=80 m^3/ha$

3.  El valor que usaremos de $q(1-\frac{\alpha}{2})$ en base a una distribución t-student con $n_{piloto}-1$ grados de libertad es 2.26.

En base a estos valores tenemos que:

$$n = {\left( \frac{q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_p)}{\hat{\varepsilon}_{(1-\alpha)\%}\hat{\mu}_{final}}\right)}^2 \rightarrow n= \left( \frac{2.26*50}{0.1*315}\right)^2 = 32.94 ~ parcelas$$

En este caso, para estar seguros redondearíamos hacia arriba por lo que deberíamos medir 33 parcelas.

**Ejemplo 2:**

Nos solicitan estimar el volumen por hectárea en un monte y dar estimaciones con un error en términos absolutos de 50 m³ por hectárea al 95% de probabilidad fiducial. Hacemos un muestreo piloto con $n_{piloto}=15$ parcelas. En base a nuestro muestreo piloto tenemos que:

1.  El valor estimado del volumen en base a las 10 parcelas piloto es $\mu_{final}=400 m³/ha$

2.  El valor estimado de la desviación típica del estimador de parcela de $sd(\hat{\mu_{final}})=125 m^3/ha$

3.  El valor que usaremos de $q(1-\frac{\alpha}{2})$ en base a una distribución t-student con $n_{piloto}-1$ grados de libertad es 2.15.

Antes de aplicar la fórmula de $n$ vamos a calcular cuanto sería el error relativo que se corresponde con un error de 50 m³ . Para ellos simplemente tenemos que recurrir a que el error relativo es el error en términos absolutos dividido por el estimador final.

$$\hat{\varepsilon}_{(1-\alpha)\%}=\frac{Error}{\hat{\mu}_{final}}$$

En este caso el error relativo sería $\hat{\varepsilon}_{(1-\alpha)\%}=\frac{Error}{\mu_{final}}=\frac{50}{400}=0.125$ y ya podríamos calcular $n$

$$n = {\left( \frac{q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_p)}{\hat{\varepsilon}_{(1-\alpha)\%}\hat{\mu}_{final}}\right)}^2 \rightarrow n= \left( \frac{2.15*125}{0.125*400}\right)^2 = 28.62 ~ parcelas$$

Para estar seguros redondearíamos hacia arriba por lo que deberíamos medir 29 parcelas.

#### Controles de la pestaña

En esta pestaña puedes cambiar el tamaño de la muestra piloto, el nivel de error relativo y el nivel de confianza o probabilidad fiducial. Cada vez que pulses el botón remuestrea se tomará una muestra piloto y se hará el cálculo de $n$. Las estimaciones de parcela se mostrarán con puntos rojos en la base de la gráfica. Una línea horizontal azul indicará el intervalo de confianza del muestreo piloto. Por otro lado, se marca el valor del estimador final con una línea negra. En torno a esta línea se añade una banda gris cuyo semi-ancho es el error relativo. También se incluye una banda malva cuyo ancho disminuye al aumentar $n$ y cuyo ancho es el error que tendríamos para distintos valores de $n$. La banda fija de color gris y la banda malva de anchura variable se cortan para el valor de $n$ que daría el error relativo deseado. Finalmente, se incluye un intervalo de confianza de color verde para el tamaño de muestra seleccionado con los controles de la izquierda. Solo se pintará este intervalo si $n$ es mayor o igual que $n_{piloto}$ y es simplemente una referencia que nos ayudará a encontrar visualmente la solución a la ecuación para calcular $n$

Se puede experimentar con el control del número de parcelas del panel de la izquierda, al mover $n$ se creará un intervalo de confianza en este caso de color verde. Puedes aumentar o reducir $n$ hasta encortar la intersección de las bandas y eso te dará el valor de $n$ que proporciona el error relativo buscado. Para valores de $n$ menores al tamaño de muestra del muestreo piloto no se mostrará nada. Finalmente, si la banda gris del error relativo requerido queda completamente incluida en la banda de anchura variable de error relativo en función de $n$ ocurre que necesitaríamos un $n$ alto (mayor que 50 que es el limite de la representación gráfica del panel derecho). Por el contrario, si la banda gris del error relativo requerido es más ancha que la banda de anchura variable del error relativo en función de $n$ , quiere decir que con el proprio muestreo piloto ya se satisface el requerimiento de precisión.

#### Comentarios sobre el cálculo de $n$

Es importante darse cuenta de que el calculo que hacemos de $n$ esta basado en estimaciones derivadas del muestreo piloto. Este muestreo se hace con un número de parcelas relativamente pequeño por lo que las estimaciones tendrán un cierto error. Esto se traduce en que el $n$ que calculemos también estará sujeto a un cierto margen de error (mayor cuanto menor sea el número de parcelas piloto) por lo que es aconsejable tomar los valores de $n$ como una referencia y estar preparados para que una vez finalicemos el trabajo con el $n$ calculado los errores sean algo distintos a los que hemos querido calcular. Si fuesen mayores de lo que nos requieren, tendríamos que añadir parcelas.

Por otro lado, en esta pestaña se muestran distintas variables. En la práctica, lo normal es tener requisitos de precisión sobre una única variable. Muchas veces estas variables son o $G$ o $V$ . Si trabajamos con $V$ hay que considerar que además de los errores de muestreo hay que ser consciente de que podremos tener errores derivados de las alometrías que usemos para calcular esta variable a nivel de árbol. Sin embargo, estos errores son difíciles de controlar y vamos a pretender que no existen. Finalmente, si tuviésemos requisitos de precisión en más de una variable tendríamos que hacer el dimensionamiento de la muestra para todas ellas y seleccionar el mayor tamaño de muestra. Esto asegurará que para el resto de las variables estaremos por debajo del umbral de error requerido.
