---
title: "Intervalos de confianza y error"
output: html_document
---

#### Introducción

En la pestaña anterior nos hemos apoyado en simulaciones del proceso de muestreo para ver que ocurre con la distribución muestral del estimador final. Repetíamos cientos de veces el proceso de muestreo y cálculo del estimador final. En esta pestaña vamos a usar menos la simulación (simularemos pero solo unas pocas veces) y **vamos a ver cómo procederíamos para calcular intervalos de confianza y errores de muestreo para el estimador final.**

Es importante en esta pestaña, que el muestreo realmente implica dos problemas de estimación. El primer problema, obtener el estimador final, ya sabemos cómo se aborda. Pero hay un segundo problema de estimación que se emplea para informar sobre la calidad del muestreo. En este segundo problema estaremos interesado en estimar la variabilidad del estimador final.

#### Notación simplificada

Para simplificar la notación vamos a usar el símbolo $\mu$ para el parámetro de interés (es un símbolo genérico), y recordamos que:

1.  Usaremos el subíndice $p$ para indicar que estamos usando el estimador de la parcela $p$ y el subíndice $final$ para indicar que consideramos un estimador final, media de $n$ estimadores de parcela.

2.  Las estimaciones de un parámetro de interés se indican poniendo un acento circunflejo sobre el símbolo del parámetro a estimar.

En base a estas reglas tenemos que, $\hat{\mu_{p}}$ sería la estimador de parcela del parámetro $\mu$ en la parcela $p$, y que $\hat{\mu}_{final}=\sum_{p=1}^n\hat{\mu}_p$ sería el estimador final del parámetro de interés $\mu$ basado en $n$ parcelas.

Cuando hagamos un inventario real mediremos $n$ parcelas y no podremos repetir ese proceso cientos de veces como hacíamos en la pestaña anterior. Entonces, **¿Cómo podemos obtener información sobre la distribución muestral del estimador final?**

El análisis de la fiabilidad del inventario se apoyará en las relaciones que existen entre la distibución muestral del estimador de parcela y la distribución muestral del estimador final prestando atención a la varianza y desviación típica de estas distribuciones. Estas relaciones se han visto en las dos pestañas anteriores.

**Es importante tener en cuenta que al realizar nuestro inventario mediremos** $n$ **parcelas y haremos su media por lo que sólo tendremos un valor del estimador final. Con un único valor será imposible analizar su variabilidad por lo que tendremos que hacer uso de las relaciones que hemos estudiado entre estimador final y estimador de parcela de los que tenemos** $n$ valores**.**

#### Relaciones entre las distribuciones muestrales del estimador de parcela y el estimador final.

Hemos visto en pestañas anteriores que

1.  La esperanza del estimador final es la esperanza del estimador de parcela.

$$
E(\hat{\mu}_{final})=E(\hat{\mu}_p)
$$

2.  Si el parámetro de interés es un total o total por unidad de área y se pueden despreciar los efectos de borde esta esperanza coincide además con el parámetro a estimar, es decir no hay sesgo:

$$
E(\hat{\mu}_{final})=E(\hat{\mu}_p)=\mu
$$

3.  Por la independencia en la aleatorización de la ubicación de las $n$ parcelas, la desviación típica (se indica con sd de standard deviation) del estimador de final es la desviación típica del estimador de parcela dividida por la raíz cuadrada del número de parcelas que se promedian en el estimador final.

$$
sd(\hat{\mu}_{final})=\frac{sd(\hat{\mu}_p)}{\sqrt{n}}
$$

4.  Para $n$ grande (no podemos saber cómo de grande ha de ser $n$), se tiene que la distribución muestral del estimador final sera una normal

$$
    \hat{\mu}_{final}\sim N(E(\hat{\mu}_p),\frac{sd(\hat{\mu}_p)²}{n})
$$

5.  Por la propiedad 2, si el parámetro de interés es un total o total por unidad de área y se pueden despreciar los efectos de borde, dicha distribución normal estará, además, centrada en el parámetro de interés $\mu$:

$$
    \hat{\mu}_{final}\sim N(\mu,\frac{sd(\hat{\mu}_p)²}{n})
$$

#### Segundo problema de estimación

El recordatorio de conceptos que acabamos de realizar nos pone en disposición de abordar el segundo problema de estimación. En este segundo problema estaremos interesados en estimar la variabilidad del estimador final y que se presentó en la pestaña 5. Esta variabilidad la medimos con la desviación típica, por lo que el segundo problema de estimación consistirá en estimar $sd(\hat{\mu}_{final})$.

Para estimar $sd(\hat{\mu}_{final})$ nos apoyaremos en la propiedad 3. De estadística conocemos que podemos obtener un estimador insesgado de la varianza de una variable aleatoria, la varianza es el cuadrado de sd, a partir de $n$ realizaciones independientes de dicha variable empleando la siguiente fórmula:

$$\hat{V}(\hat{\mu}_p)=\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n-1}$$

Podemos tomar raíces cuadradas para convertir varianzas estimadas en desviaciones típicas estimadas:

$$\hat{sd}(\hat{\mu}_p)=\sqrt{\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n-1}}$$

**IMPORTANTE:** Las varianzas y desviaciones típicas de las dos fórmulas anteriores son estimadas, por eso llevan un acento circunflejo.

Ya casi hemos terminado el segundo problema de estimación, en base a la última ecuación y a la propiedad 3, tendremos que:

$$\hat{V}(\hat{\mu}_{final})=\frac{\hat{V}(\hat{\mu}_p)}{n}=\frac{1}{n}\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n-1}=\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n(n-1)}$$

y para desviaciones típicas tendremos:

$$\hat{sd}(\hat{\mu}_{final})=\frac{\hat{sd}(\hat{\mu}_p)}{\sqrt{n}}=\frac{\sqrt{\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n-1}}}{\sqrt{n}}=\sqrt{\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n(n-1)}}$$

#### Intervalos de confianza

Una vez que hemos visto el segundo problema de estimación (estimar la dispersión de la distribución muestral del estimador final a través de la varianza o desviación ), podemos ver como se hace el reporte de incertidumbres o control de calidad de un muestreo. Para ello, nos vamos a apoyar en los estimadores de la desviación típica que acabamos de ver y en la aplicación del teorema del límite central que veíamos en la pestaña anterior.

Asumiendo que se ha conseguido la normalidad, la siguiente fórmula nos permite crear intervalos que contienen el valor esperado del estimador final con un $(1-\alpha)\%$ de probabilidad:

$$Intervalo \: confianza=[\hat{\mu}_{final}-q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})\:,\:\hat{\mu}_{final}+q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})]$$

A $(1-\alpha)\%$ se le llama nivel de confianza o probabilidad fiducial y normalmente se establece en un 95% es decir $\alpha=0.05$.

Una forma alternativa y más concisa de expresar estos intervalos es

$$Intervalo \: confianza=\hat{\mu}_{final}\pm q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})$$

**IMPORTANTE:** Cuando estimamos totales o totales por unidad de área, el valor esperado de $\hat{\mu}_{final}$ coincidirá con $\mu_{final}$ (ausencia de sesgo). En este caso, si fuésemos capaces de repetir muchas veces el proceso de muestreo, los intervalos de confianza construidos contendrían el valor que queremos estimar en un $1-\alpha\%$ de las ocasiones. Para otros parámetros, el valor esperado de $\hat{\mu}_{final}$ no tiene porqué coincidir con $\mu$ por lo que los intervalos no tienen porque contener el parámetro de interés un $1-\alpha\%$ de las veces.

#### Cálculo de los intervalos

Sabemos calcular todos los factores del intervalo salvo uno, el factor $q(1-\frac{\alpha}{2})$ . Distintos autores consideran distintos valores para $q(1-\frac{\alpha}{2})$:

1.  Algunos autores, como por ejemplo Särndal (2003), hace que $q(1-\frac{\alpha}{2})$ sea igual al cuantil de probabilidad $1-\frac{\alpha}{2}$ de una distribución normal estándar.

2.  Otros autores se ponen del lado de la seguridad y usan $q(1-\frac{\alpha}{2})=t(1-\frac{\alpha}{2},n-1)$ , donde $t(1-\frac{\alpha}{2},n-1)$ es el cuantil de probabilidad $1-\frac{\alpha}{2}$ de una distribución tipo t-student con $n-1$ grados de libertad (recuerda que $n$ es el número de parcelas).

La fórmula 2 se suele preferir por hacer intervalos un poco más anchos, pero desde el punto de vista teórico ambas son aproximaciones ya que nunca podremos saber cuando se consigue la convergencia a una distribución normal. En ambos casos, para un nivel de confianza del 95%, $1-\alpha\%=95\%$, y con un número de parcelas superior 5 tendremos que los valores de $q(1-\frac{\alpha}{2})$ estarán comprendidos entre 1.96 y 2.57. La opción 1 da el valor de 1.96 y la opción 2 da valores mayores a 1.96 pero que se acercan a 1.96 a medida que aumenta $n$

En la práctica, el proceso de construcción de los intervalos de confianza se realiza de las siguiente manera.

1.  Obtenemos el estimador final $\hat{\mu}_{final}$ como promedio de los estimadores $n$ de parcela.
2.  Estimamos la desviación típica de $\hat{\mu}_{final}$ usando:

$$\hat{sd}(\hat{\mu}_{final})=\sqrt{\frac{\sum_{p=1}^n(\hat{\mu}_p-\hat{\mu}_{final})^2}{n(n-1)}}$$

3.  Elegimos una opción para q y construimos el intervalo de confianza como:

$$Intervalo \: confianza=\hat{\mu}_{final}\pm q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})$$

#### Error de muestreo

Directamente relacionado con los intervalos de confianza tendremos la cantidad que llamamos error de muestreo. El error de muestreo para un nivel de probabilidad $1-\alpha\%$ es la cantidad que sustraemos o añadimos a $\hat{\mu}_{final}$ al construir el intervalo. Es decir, el error de muestreo es la mitad del ancho del intervalo de confianza.

$$Error\: muestreo_{(1-\alpha)\%} = q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})$$

Normalmente los errores de muestreo no se expresan en términos absolutos si no que los referiremos a la magnitud a estimar. Como esta magnitud no la conocemos, la sustituiremos por $\hat{\mu}_{final}$ . A estos errores los llamamos errores relativos de muestreo y los denotaremos con el símbolo $\hat{\varepsilon}_{(1-\alpha)\%}$ y los calcularemos, expresándolos en tanto por uno, con la siguiente fórmula:

$$\hat{\varepsilon}_{(1-\alpha)\%} = \frac{q(1-\frac{\alpha}{2})\hat{sd}(\hat{\mu}_{final})}{\hat{\mu}_{final}}$$

Los términos que intervienen en el error de muestreo (en términos absolutos o relativos) implican los pasos 1, 2 y 3 de la construcción de intervalos de confianza, en este sentido no hay nada nuevo. Pondremos el acento circunflejo en el error de muestreo para indicar que es una magnitud estimada (Esto también se debería hacer con los intervalos pero la notación queda algo engorrosa)

**IMPORTANTE:** Es frecuente que se soliciten trabajos de muestreo donde se especifica una tolerancia máxima en términos de error. Generalmente esta especificación se hace en términos de error relativo. Por ejemplo, nos podrían solicitar realizar un muestreo donde el volumen se estimase con un error relativo de muestreo inferior al 10% considerando un nivel de confianza del 95%. Ante esta situación podríamos ir midiendo más y más parcelas hasta que alcanzásemos el error deseado. **Esto** **NO es lo que se hace en la práctica!!** En la siguiente pestaña veremos como calcular el número de parcelas a medir para verificar este tipo de condiciones.

#### Controles de la aplicación

En esta pestaña, para el número de parcelas indicado, se repite el muestreo cinco veces. En el panel derecho, parte inferior, podemos ver en negro el valor teórico de $sd(\hat{\mu}_{final})$, en azul se mostrarán las 5 estimaciones de $\hat{sd}(\hat{\mu}_{final})$ . En el panel derecho, se muestran para cada una de las cinco replicaciones, $\hat{sd}(\hat{\mu}_{p})$, $\hat{sd}(\hat{\mu}_{final})$ (texto rojo y a la izquierda), el intervalo de confianza para $\hat{\mu}_{final}$ (en rojo y forma gráfica) y el error de muestreo (texto azul a la derecha). En rojo y con una ligera transparencia se muestra los $n$ valores de $\hat{\mu}_{p}$ para cada replica.

En el panel izquierdo tendremos los valores de los parámetros de interés a estimar, un control para aumentar o reducir el nivel de confianza $(1-\alpha)\%$ y un botón que dice **Remuestrea** y que al ser pulsado descartará las cinco replicas de $n$ parcelas y tomará otras cinco nuevas. En esta pestaña el botón **Muestrea** no hará nada pero los controles para el tipo de parcela, densidad, tamaño del área a muestrear y número de parcelas seguirán activos.

#### Referencias

Särndal, C.-E., Swensson, B., Wretman, J., 2003. Model Assisted Survey Sampling (Springer Series in Statistics).
