---
title: "Estimación con una parcela ubicada uniformemente al azar"
output: html_document
---

En esta pestaña se explica cómo se hace la estimación de un parámetro de interés (ver pestaña Población) cuando se considera el experimento aleatorio de:

1.  Seleccionar una ubicación al azar en la zona a muestrear

2.  Seleccionar los árboles que compondrán la muestra en base al tipo de parcela empleado

3.  Calcular estimaciones de parcela a partir del conjunto de árboles seleccionados

La base de la estimación será el estimador de Horvitz-Thompson para totales o su versión para totales por unidad de área. Ambas versiones pueden intercambiarse casi de forma directa ya que el área a muestrear $A$ normalmente es conocida.

Antes de continuar, se recomienda pulsar el botón **Regenera población** para no acumular muestras de las pruebas realizadas en pestañas anteriores.

#### Parámetros de interés

***Totales***

De forma genérica, un total se define como la suma de una variable de interés $y_i$ para todo los árboles $i$ de la zona a muestrear. Un total por unidad de área simplemente consiste en dividir el total por el área muestreada. Si usamos el símbolo $\cal{N}$ (**N de bordes redondeados**) para representar el número de árboles en la zona a muestrear (**parámetro desconocido**) tenemos que totales y totales por unidad de área se expresan como:

$$
Total(y)=\sum_{i=1}^{\cal{N}}y_i \qquad \qquad Total\:por\:unidad\:area(y)=\frac{1}{A}\sum_{i=1}^{\cal{N}}y_i
$$

Dos ejemplos de totales por unidad de área son la densidad $N$ y el área basimétrica $G$. Para la densidad, $N$ (**N con bordes rectos**), $y_i$ es igual a 1 para todos los árboles, para $G$, $y_i$ es la sección normal (en metros cuadrados) de cada árbol.

***Funciones de totales***

Si bien los totales son, seguramente, los parámetros de interés más importantes desde el punto de los inventarios. Muchas variables dasométricas que querremos estimar no son totales si no funciones que implican más de un total. En este sentido destacan los valores medios.

$$
Media(y)=\frac{\sum_{i=1}^{\cal{N}}y_i}{\cal{N}}=\frac{\sum_{i=1}^{\cal{N}}y_i}{\sum_{i=1}^{\cal{N}}1}
$$

Pero $\cal{N}$ es en sí un total donde $y_i$ es uno para todos los árboles, de forma que **los valores medios son ratios de totales**.

Otro ejemplo de parámetro de interés que se expresa como función de totales es el diámetro cuadrático medio $d_g$. Partiendo de la propia definición de $d_g$ o diámetro del árbol de sección normal media. Vemos que $d_g$ es una función de dos totales $G$ y $N$

$$
\frac{\pi d_g^2}{4}=\frac{AG}{AN} \rightarrow d_g = \sqrt{\frac{4G}{\pi N}}
$$

***Otros parámetros complejos***

Hay variables dasométricas que no son totales o funciones o ratios de totales. En este apartado destacan las alturas y diámetros dominantes, que suelen definirse como alturas o diámetros medios del conjunto de árboles dominantes.

$$
h_o= \frac{1}{\cal{N_{dominantes}}}\sum\limits_{i\in dominantes}h_i
$$

$$
d_o= \frac{1}{\cal{N_{dominantes}}}\sum\limits_{i\in dominantes}d_i
$$

Bajo el criterio de Assman, el conjunto de árboles dominantes es el conjunto de los 100 individuos con mayor diámetro de la hectárea. Estos parámetros, cuya definición es aparentemente sencilla, implican trabajar con un conjunto de árboles (el conjunto de los árboles dominantes) que es desconocido y la propia definición puede ser confusa. Por ejemplo, ¿Cómo establecemos la altura dominante de una masa de 1 ha de superficie donde hay 50 árboles?. En principio, no vamos a preocuparnos de estos detalles, pero es importante saber que existen y que en algún momento los encontraremos tendremos que decidir como aproximarnos a dichos problemas.

#### Estimador de Horvitz-Thompson de parcela para totales o totales por unidad de área.

En esta sección se explica como se obtienen estimaciones de parcela (panel central y medio) a partir de las mediciones de árboles (panel izquierdo).

Cuando nuestro objetivo es estimar un total o un total por unidad de área emplearemos el estimador de parcela de Horvitz-Thompson aunque a partir de ahora simplemente nos referiremos a este estimador como estimador de parcela para totales o totales por unidad de área.

Para indicar estimaciones, añadiremos el acento circunflejo \^ sobre el parámetro de interés.

$$
\hat{Total(y)}=\begin{cases}
\sum\limits_{i\in muestra}\frac{y_i}{\pi_i} , & \text{si se ha seleccionado algún árbol} \\
 & \\
0, & \text{si la no se ha seleccionado ningún árbol}
\end{cases}
$$

$$
\hat{Total\:por\:unidad\:area(y)}=\begin{cases}
\frac{1}{A}\sum\limits_{i\in muestra}\frac{y_i}{\pi_i} = \sum\limits_{i\in muestra}\frac{y_i}{A\frac{a_{parcela}}{A}} = \sum\limits_{i\in muestra}y_iw_i , & \text{si se ha seleccionado algún árbol} \\
 & \\
0, & \text{si la no se ha seleccionado ningún árbol}
\end{cases}
$$

**Es importante mencionar dos cuestiones. Primero, ambos estimadores son igual a cero si la muestra está vacía (es decir si no se ha seleccionado ningún árbol). Por otro lado, para totales por unidad de área, cuando estimamos totales por unidad de área, el área a muestrear** $A$**, aparece dividiendo al total, pero también aparece de forma implícita en las** $\pi_i$ **. Estas áreas se cancelan y el estimador tiene una forma sumamente sencilla donde lo único que hay que hacer es sumar, para todos los árboles de la parcela, el valor de la variable de interés por su factor de expansión.**

$$\hat{Total\:por\:unidad\:area(y)}=\begin{cases}
\sum\limits_{i\in muestra}y_iw_i  , & \text{si se ha seleccionado algún árbol} \\
 & \\
0, & \text{si la no se ha seleccionado ningún árbol}
\end{cases}
$$

**Si recordamos la interpretación de factor de expansión como número de árboles similares al árbol muestreado que esperamos encontrar en una hectárea de terreno podemos deducir la fórmula anterior recordando que total por unidad de área es la suma de la variable de interés para todos los árboles de la hectárea. Como cada árbol muestreado representa** $w_i$ **árboles en la hectárea de terreno, lo único que hay que hacer es sumar la variable de interés** $y_i$ **por** $w_i$

**En el panel izquierdo de esta pestaña tienes las mediciones a nivel de árbol que se haría en la parcela. Para obtener un determinado total por unidad de área solo tenemos que multiplicar la columna de la variable para la que queremos hacer el total por unidad de área (si queremos estimar** $N$ **esta columna siempre valdría 1) por el factor de expansión correspondiente y sumar.**

**Ejemplo 1:**

$$
\hat{G}=\begin{cases}
\sum\limits_{i\in muestra}g_iw_i  , & \text{si se ha seleccionado algún árbol} \\
 & \\
0, & \text{si no se ha seleccionado ningún árbol}
\end{cases}
$$

**Ejemplo 2:**

$$
\hat{N}=\begin{cases}
\sum\limits_{i\in muestra}1w_i  , & \text{si se ha seleccionado algún árbol} \\
 & \\
0, & \text{si la no se ha seleccionado ningún árbol}
\end{cases}
$$

#### Estimador de parcela para ratios y funciones de totales

Cuando consideremos la estimación de parámetros medios (ratios de totales) o funciones de totales, simplemente haremos el estimador de parcela para cada uno de los totales.

**Ejemplo 3:**

Si el parámetro de interés es la altura media

$$\bar{h}=\frac{\sum_{i=1}^{\cal{N}}y_i}{\cal{N}}=\frac{\frac{1}{A}\sum_{i=1}^{\cal{N}}y_i}{\frac{1}{A}\sum_{i=1}^{\cal{N}}1}$$

La altura media es el ratio de dos totales por unidad de área, el total de las alturas $y_i\rightarrow h_i$ y $N$ (el total de una variable que vale 1 para todos los árboles. En este caso, simplemente haremos el estimador de parcela para el numerador y el estimador por parcela para el denominador y después haremos el ratio.

$$
\hat{\bar{h}}=\frac{\sum\limits_{i\in muestra}h_iw_i}{\sum\limits_{i\in muestra}1w_i}
$$

**Ejemplo 4:**

Para estimar $d_g$ estimaremos $G$ y $N$ tal como se hace en los ejemplos 1 y 2, y después sustituiremos en la ecuación de $d_g$ para obtener el estimador de parcela.

$$
\hat{d_g} = \sqrt{\frac{4\hat{G}}{\pi \hat{N}}}
$$

#### Estimador de parcela para parámetros complejos (alturas y diámetros dominantes)

Para alturas y diámetros dominantes, la estimación se hará construyendo análogos de parcela. En este caso, lo primero que haremos será ordenar la tabla de mediciones por diámetro en orden decreciente. Después, iremos sumando los factores de expansión hasta alcanzar 100 árboles por hectárea. Esto nos permitirá estimar el conjunto de árboles dominantes de la parcela. Una vez tengamos este conjunto $\hat{dominantes}$ simplemente calcularemos los valores medios como hemos hecho en el ejemplo 3, pero trabajando sobre el conjunto de los árboles dominantes.

$$
\hat{h_o}= \frac{\sum\limits_{i\in \hat{dominantes}}h_iw_i}{\sum\limits_{i\in \hat{dominantes}}w_i}
$$

y

$$
\hat{d_o}= \frac{\sum\limits_{i\in \hat{dominantes}}d_iw_i}{\sum\limits_{i\in \hat{dominantes}}w_i}
$$

Si se quiere ser muy fiel a la definición de árboles dominantes de Assman, para el último árbol sumado, deberíamos reducir el factor de expansión de forma que la suma de todos los factores de expansión para el conjunto de árboles dominante sea 100 (podemos usar el símbolo $w_i^*$ para indicar que estos factores de expansión se han modificado para el último árbol dominante). La suma del denominador, en este caso se reduce a 100 árboles en una hectárea.

$$
\hat{h_o}= \frac{\sum\limits_{i\in \hat{dominantes}}h_iw_i^*}{\sum\limits_{i\in \hat{dominantes}}w_i^*}\frac{\sum\limits_{i\in \hat{dominantes}}h_iw_i^*}{100}
$$ y

$$
\hat{d_o}= \frac{\sum\limits_{i\in \hat{dominantes}}d_iw_i^*}{\sum\limits_{i\in \hat{dominantes}}w_i^*}=\frac{\sum\limits_{i\in \hat{dominantes}}d_iw_i^*}{100}
$$

#### **Propiedades del estimador de parcela**

#### [Valor esperado]{.underline}

Cuando consideramos totales o totales por unidad de área, es posible demostrar que el estimador de parcela que hemos empleado no tendrá sesgo si los efectos de borde no son importantes. Es decir, si los efectos de borde se pueden despreciar, tenemos que el valor esperado del estimador coincide con el valor que queremos estimar.

$$
\boxed{\boxed{ E(\hat{Total(y)}) = Total(y)}}
$$

Si pudiésemos repetir infinitas veces el proceso de seleccionar muestras y calcular el estimador, la media de esas infinitas estimaciones coincidiría con el valor a estimar. **Esta propiedad es muy fuerte pues se cumple sea cual sea la población y el tipo de parcela, lo único que debe ser despreciable son los efectos de borde, cosa que normalmente ocurre.**

Desafortunadamente, esta propiedad aplica a los estimadores de totales y totales por unidad de área cuando los efectos de borde son despreciables. **Para ratios y funciones de totales y parámetros complejos, no podemos asegurar la ausencia de sesgo.**

#### [Varianza y desviación típica]{.underline}

Hemos visto como funcionan los estimadores de parcela en términos de sesgo. Sin embargo, el sesgo no es lo único que nos interesa. La varianza o desviación típica del estimador nos dan una idea de la dispersión del mismo. Desafortunadamente, la varianza de los estimadores de parcela están directamente relacionados con las disposición espacial de los árboles y esto es imposible de conocer, **por lo que sólo podemos aspirar a estimar estas varianzas repitiendo múltiples veces el experimento de seleccionar una parcela al azar.**

#### Repetición del experimento de ubicar una parcela al azar (Panel derecho)

Como puente al proceso más realista en el que se miden múltiples parcelas, podemos ver que ocurre si repetimos múltiples veces el proceso de seleccionar un punto, tomar la muestra de árboles y calcular los estimadores correspondientes.

En la parte superior (en rojo) se puede ver como se van distribuyendo las estimaciones de parcela para cinco variables a medida que repetimos el proceso de muestreo. El valor real del parámetro de interés, (que podemos conocer porque trabajamos con una población simulada) se marca con una linea vertical roja. El promedio de todas las estimaciones que vayamos realizando se indica con un punto grueso de color azul.

[En este panel es importante observar dos cosas:]{.underline}

Para totales, a medida que hacemos más y más parcelas y tomamos la media, el punto azul se aproxima más y más al parámetro de interés. Si el lado de tu población es pequeño, puede que haya cierta desviación sistemática o sesgo ya que las probabilidades de inclusión o factores de expansión que tomamos no consideran efectos de bordes que se dan cuando el área de inclusión de un árbol corta los límites de la zona a muestrear.

En aplicaciones prácticas las áreas a muestrear son grandes y estos efectos de borde tienden a ser pequeños, algo similar ocurre si se aumenta el lado del área simulada, estos efectos de borde tienden a tener una importancia casi nula. Prueba a generar poblaciones con un lado mayor:

-   **En la pestaña** **Selección de muestra** verás que, proporcionalmente, las áreas de inclusión que cortan el área muestreada pierden importancia

-   **En esta pestaña** podrás ver como la media de estimaciones de totales por unidad de área se aproximan más y más al valor real, es decir, el sesgo para totales desaparece. Finalmente, a medida que añadimos más muestras, la media varia cada vez menos mientras que la variabilidad de las estimaciones de parcela se mantiene dentro de un rango más amplio. En las siguientes pestañas se puede ver la relación entre la variabilidad de la estimación por parcela y la variabilidad de una media de $n$ parcelas.
