---
title: "Poblacion"
output: html_document
---

#### Introducción

**Estás viendo la población simulada**. Al hacer un inventario, no conocemos la población, no sabemos cuantos individuos hay, ni cuales son los valores de sus alturas, diámetros, etc. Esto implica que en aplicaciones reales no conoceremos los valores de los parámetros de interés que querremos estimar. Sin embargo, las simulaciones son útiles para acercarnos al problema del muestreo en unas condiciones donde conocemos todos los individuos en el área a muestrear (cuadrado rojo), y podemos calcular todos los parámetros de interés para posteriormente analizar distintas configuraciones del muestreo.

#### Parámetros de interés (General)

En esta pestaña puedes ver distintos parámetros de interés y podrás diferenciar entre totales, totales por unidad de área, valores medios, etc. La aplicación te permite configurar distintas poblaciones y obtener una tabla con todos los individuos de dicha población que puedes usar para calcular distintas variables de masa.

En la aplicación se consideran los siguientes tipos de parámetros de interés:

1.  Totales y totales por unidad de área

2.  Valores medios, ratios y funciones de totales

3.  Parámetros complejos (valores dominantes)

#### Totales y totales por unidad de área

De forma genérica, un total se define como la suma de una variable de interés $y_i$ para todo los árboles $i$ de la zona a muestrear. Un total por unidad de área simplemente consiste en dividir un total por el área muestreada $A$ . Si usamos el símbolo $\cal{N}$ (con bordes redondeados) para representar el número de árboles en la zona a muestrear (parámetro desconocido en aplicaciones reales) tenemos que totales y totales por unidad de área se expresan como:

$$Total(y)=\sum_{i=1}^{\cal{N}}y_i \qquad \qquad Total \: por \: unidad\:area(y)=\frac{1}{A}\sum_{i=1}^{\cal{N}}y_i$$

Dos ejemplos de totales por unidad de área son la densidad $N$ y el área basimétrica $G$. Para la densidad, $N$ (con bordes rectos), $y_i$ es igual a 1 para todos los árboles, para $G$, $y_i$ es la sección normal (en metros cuadrados) de cada árbol.

**Ejemplos de totales**

-   Si consideramos una variable que valga 1 para todos los árboles $y_i=1$ tenemos que el tamaño de la población $\cal{N}$ es el total de dicha variable (al sumar 1 por cada individuo es como si estuviésemos contándolos). Esta variable es el total de individuos.

$$Total\:individuos= \sum_{i=1}^{\cal{N}}1$$

-   Total secciones normales

$$Total\:secciones\:normales(m²)=\sum_{i=1}^{\cal{N}}g_i=\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i^2$$

-   Total de volumen con corteza

$$Total\:volumen\:con\:corteza(m³)=\sum_{i=1}^{\cal{N}}vcc_i$$

**Ejemplos de totales por unidad de área**

A continuación tenemos las variantes por unidad de área de los totales anteriores. La diferencia con los totales, es que referimos las sumas a la unidad de área. Normalmente usamos la hectárea como unidad de área, por lo que $A$ en las siguientes fórmulas es el área en hectáreas de la zona a muestrear.

-   Densidad (pies por ha) (Total por unidad de área)

$$N(individuos/ha)=\frac{1}{A}\sum_{i=1}^{\cal{N}}1$$

-   Área basimétrica (Total por unidad de área)

$$G(m²/ha)=\frac{1}{A}\sum_{i=1}^{\cal{N}}g_i=\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i^2$$

-   Volumen con corteza por unidad de área (Volumen con corteza por ha)

$$VCC(m³/ha)=\frac{1}{A}\sum_{i=1}^{\cal{N}}vcc_i$$

#### Ratios y funciones de totales

Si bien los totales son, seguramente, los parámetros de interés más importantes desde el punto de los inventarios. Muchas variables dasométricas que querremos estimar no son totales si no funciones que implican a más de un total. En este sentido destacan los valores medios.

$$
Media(y)=\frac{\sum_{i=1}^{\cal{N}}y_i}{\cal{N}}=\frac{\sum_{i=1}^{\cal{N}}y_i}{\sum_{i=1}^{\cal{N}}1}
$$

Pero $\cal{N}$ es en sí un total donde $y_i$ es uno para todos los árboles, de forma que los valores medios son ratios de totales.

Otro ejemplo de parámetro de interés que se expresa como función de totales es el diámetro cuadrático medio $d_g$. Partiendo de la propia definición de $d_g$ o diámetro del árbol de sección normal media. Vemos que $d_g$ es una función de dos totales $G$ y $N$

$$
\frac{\pi d_g^2}{4}=\frac{AG}{AN} \rightarrow d_g = \sqrt{\frac{4G}{\pi N}}
$$

**Ejemplos de ratios y funciones de totales o totales por unidad de área**

-   Diámetro cuadrático medio (función de totales)

$$dg(cm)=\sqrt{\frac{4}{\pi}\frac{G}{N}}=\sqrt{\frac{4}{\pi}\frac{\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i^2}{\frac{1}{A}\sum_{i=1}^{\cal{N}}1}}$$

-   Altura media (ratio de totales)

$$\bar{h}(m)=\frac{\sum_{i=1}^{\cal{N}}h_i}{\sum_{i=1}^{\cal{N}}1}$$

#### Otros parámetros complejos

Hay variables dasométricas que no son totales o funciones o ratios de totales. En este apartado destacan las alturas y diámetros dominantes, que suelen definirse como alturas o diámetros medios del conjunto de árboles dominantes.

$$
h_o= \frac{1}{\cal{N_{dominantes}}}\sum\limits_{i\in dominantes}h_i
$$

$$
d_o= \frac{1}{\cal{N_{dominantes}}}\sum\limits_{i\in dominantes}d_i
$$

Bajo el criterio de Assman, el conjunto de árboles dominantes es el conjunto de los 100 individuos con mayor diámetro de la hectárea. Estos parámetros, cuya definición es aparentemente sencilla, implican trabajar con un conjunto de árboles (el conjunto de los árboles dominantes) que es desconocido y la propia definición puede ser confusa. Por ejemplo, ¿Cómo establecemos la altura dominante de una masa de 1 ha de superficie donde hay 50 árboles?. En principio, no vamos a preocuparnos de estos detalles, pero es importante saber que existen y que en algún momento los encontraremos tendremos que decidir como aproximarnos a dichos problemas. Sin que es importante tener en cuenta que desde el punto de vista del muestreo, estos parámetros no son totales ni valores medios al uso, ya que se refieren a una fracción de la población.
